/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@elegant-router/types";

export const layouts: Record<RouteLayoutKey, RawRouteComponent> = {
  base: () => import("@/layouts/base-layout/index.vue"),
  blank: () => import("@/layouts/blank-layout/index.vue"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  403: () => import("@/views/(builtin)/403/index.vue"),
  404: () => import("@/views/(builtin)/404/index.vue"),
  500: () => import("@/views/(builtin)/500/index.vue"),
  About: () => import("@/views/about/index.vue"),
  AlovaRequest: () => import("@/views/alova/request/index.vue"),
  AlovaScenes: () => import("@/views/alova/scenes/index.vue"),
  FunctionMultiTab: () => import("@/views/function/multi-tab/index.vue"),
  FunctionRequest: () => import("@/views/function/request/index.vue"),
  FunctionSuperPage: () => import("@/views/function/super-page/index.vue"),
  FunctionTab: () => import("@/views/function/tab/index.vue"),
  FunctionToggleAuth: () => import("@/views/function/toggle-auth/index.vue"),
  Home: () => import("@/views/home/index.vue"),
  IframePageUrl: () => import("@/views/(builtin)/iframe-page/[url].vue"),
  Login: () => import("@/views/(builtin)/login/index.vue"),
  ManageMenu: () => import("@/views/manage/menu/index.vue"),
  ManageRole: () => import("@/views/manage/role/index.vue"),
  ManageUser: () => import("@/views/manage/user/index.vue"),
  ManageUserDetailId: () => import("@/views/manage/user-detail/[id].vue"),
  PluginBarcode: () => import("@/views/plugin/barcode/index.vue"),
  PluginChartsAntv: () => import("@/views/plugin/charts/antv/index.vue"),
  PluginChartsEcharts: () => import("@/views/plugin/charts/echarts/index.vue"),
  PluginChartsVchart: () => import("@/views/plugin/charts/vchart/index.vue"),
  PluginCopy: () => import("@/views/plugin/copy/index.vue"),
  PluginEditorMarkdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  PluginEditorQuill: () => import("@/views/plugin/editor/quill/index.vue"),
  PluginExcel: () => import("@/views/plugin/excel/index.vue"),
  PluginGanttDhtmlx: () => import("@/views/plugin/gantt/dhtmlx/index.vue"),
  PluginGanttVtable: () => import("@/views/plugin/gantt/vtable/index.vue"),
  PluginIcon: () => import("@/views/plugin/icon/index.vue"),
  PluginMap: () => import("@/views/plugin/map/index.vue"),
  PluginPdf: () => import("@/views/plugin/pdf/index.vue"),
  PluginPinyin: () => import("@/views/plugin/pinyin/index.vue"),
  PluginPrint: () => import("@/views/plugin/print/index.vue"),
  PluginSwiper: () => import("@/views/plugin/swiper/index.vue"),
  PluginTablesVtable: () => import("@/views/plugin/tables/vtable/index.vue"),
  PluginTypeit: () => import("@/views/plugin/typeit/index.vue"),
  PluginVideo: () => import("@/views/plugin/video/index.vue"),
  ProNaiveConfigProvider: () => import("@/views/pro-naive/ConfigProvider.vue"),
  ProNaiveFormBasic: () => import("@/views/pro-naive/form/basic/index.vue"),
  ProNaiveFormQuery: () => import("@/views/pro-naive/form/query/index.vue"),
  ProNaiveFormStep: () => import("@/views/pro-naive/form/step/index.vue"),
  ProNaiveTableRemote: () => import("@/views/pro-naive/table/remote/index.vue"),
  ProNaiveTableRowEdit: () => import("@/views/pro-naive/table/row-edit/index.vue"),
  UserCenter: () => import("@/views/user-center/index.vue"),
  Wip: () => import("@/views/(builtin)/wip/index.vue"),
};
