/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: 'Root',
    path: '/',
    redirect: '/home',
    meta: {
      title: "Root"
    },
  },
  {
    name: 'NotFound',
    path: '/:pathMatch(.*)*',
    layout: 'base',
    component: '404',
    meta: {
      title: "NotFound"
    },
  },
  {
    name: '403',
    path: '/403',
    layout: 'base',
    component: '403',
    meta: {
      title: "403",
      constant: true
    },
  },
  {
    name: '404',
    path: '/404',
    layout: 'base',
    component: '404',
    meta: {
      title: "404",
      constant: true
    },
  },
  {
    name: '500',
    path: '/500',
    layout: 'base',
    component: '500',
    meta: {
      title: "500",
      constant: true
    },
  },
  {
    name: 'About',
    path: '/about',
    layout: 'base',
    component: 'About',
    meta: {
      title: "About"
    },
  },
  {
    name: 'AlovaRequest',
    path: '/alova/request',
    layout: 'base',
    component: 'AlovaRequest',
    meta: {
      title: "AlovaRequest"
    },
  },
  {
    name: 'AlovaScenes',
    path: '/alova/scenes',
    layout: 'base',
    component: 'AlovaScenes',
    meta: {
      title: "AlovaScenes"
    },
  },
  {
    name: 'DocumentAlova',
    path: '/document/alova',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentAlova"
    },
  },
  {
    name: 'DocumentAntd',
    path: '/document/antd',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentAntd"
    },
  },
  {
    name: 'DocumentNaive',
    path: '/document/naive',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentNaive"
    },
  },
  {
    name: 'DocumentProject',
    path: '/document/project',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentProject"
    },
  },
  {
    name: 'DocumentProjectLink',
    path: '/document/project-link',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentProjectLink"
    },
  },
  {
    name: 'DocumentProNaive',
    path: '/document/pro-naive',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentProNaive"
    },
  },
  {
    name: 'DocumentUnocss',
    path: '/document/unocss',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentUnocss"
    },
  },
  {
    name: 'DocumentVideo',
    path: '/document/video',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentVideo"
    },
  },
  {
    name: 'DocumentVite',
    path: '/document/vite',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentVite"
    },
  },
  {
    name: 'DocumentVue',
    path: '/document/vue',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "DocumentVue"
    },
  },
  {
    name: 'Exception403',
    path: '/exception/403',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "Exception403"
    },
  },
  {
    name: 'Exception404',
    path: '/exception/404',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "Exception404"
    },
  },
  {
    name: 'Exception500',
    path: '/exception/500',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "Exception500"
    },
  },
  {
    name: 'FunctionMultiTab',
    path: '/function/multi-tab',
    layout: 'base',
    component: 'FunctionMultiTab',
    meta: {
      title: "FunctionMultiTab"
    },
  },
  {
    name: 'FunctionRequest',
    path: '/function/request',
    layout: 'base',
    component: 'FunctionRequest',
    meta: {
      title: "FunctionRequest"
    },
  },
  {
    name: 'FunctionSuperPage',
    path: '/function/super-page',
    layout: 'base',
    component: 'FunctionSuperPage',
    meta: {
      title: "FunctionSuperPage"
    },
  },
  {
    name: 'FunctionTab',
    path: '/function/tab',
    layout: 'base',
    component: 'FunctionTab',
    meta: {
      title: "FunctionTab"
    },
  },
  {
    name: 'FunctionToggleAuth',
    path: '/function/toggle-auth',
    layout: 'base',
    component: 'FunctionToggleAuth',
    meta: {
      title: "FunctionToggleAuth"
    },
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
    meta: {
      title: "Home"
    },
  },
  {
    name: 'IframePageUrl',
    path: '/iframe-page/:url',
    layout: 'base',
    component: 'IframePageUrl',
    meta: {
      title: "IframePageUrl"
    },
  },
  {
    name: 'Login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    layout: 'base',
    component: 'Login',
    meta: {
      title: "Login",
      constant: true
    },
  },
  {
    name: 'ManageMenu',
    path: '/manage/menu',
    layout: 'base',
    component: 'ManageMenu',
    meta: {
      title: "ManageMenu"
    },
  },
  {
    name: 'ManageRole',
    path: '/manage/role',
    layout: 'base',
    component: 'ManageRole',
    meta: {
      title: "ManageRole"
    },
  },
  {
    name: 'ManageUser',
    path: '/manage/user',
    layout: 'base',
    component: 'ManageUser',
    meta: {
      title: "ManageUser"
    },
  },
  {
    name: 'ManageUserDetailId',
    path: '/manage/user-detail/:id',
    layout: 'base',
    component: 'ManageUserDetailId',
    meta: {
      title: "ManageUserDetailId"
    },
  },
  {
    name: 'PluginBarcode',
    path: '/plugin/barcode',
    layout: 'base',
    component: 'PluginBarcode',
    meta: {
      title: "PluginBarcode"
    },
  },
  {
    name: 'PluginChartsAntv',
    path: '/plugin/charts/antv',
    layout: 'base',
    component: 'PluginChartsAntv',
    meta: {
      title: "PluginChartsAntv"
    },
  },
  {
    name: 'PluginChartsEcharts',
    path: '/plugin/charts/echarts',
    layout: 'base',
    component: 'PluginChartsEcharts',
    meta: {
      title: "PluginChartsEcharts"
    },
  },
  {
    name: 'PluginChartsVchart',
    path: '/plugin/charts/vchart',
    layout: 'base',
    component: 'PluginChartsVchart',
    meta: {
      title: "PluginChartsVchart"
    },
  },
  {
    name: 'PluginCopy',
    path: '/plugin/copy',
    layout: 'base',
    component: 'PluginCopy',
    meta: {
      title: "PluginCopy"
    },
  },
  {
    name: 'PluginEditorMarkdown',
    path: '/plugin/editor/markdown',
    layout: 'base',
    component: 'PluginEditorMarkdown',
    meta: {
      title: "PluginEditorMarkdown"
    },
  },
  {
    name: 'PluginEditorQuill',
    path: '/plugin/editor/quill',
    layout: 'base',
    component: 'PluginEditorQuill',
    meta: {
      title: "PluginEditorQuill"
    },
  },
  {
    name: 'PluginExcel',
    path: '/plugin/excel',
    layout: 'base',
    component: 'PluginExcel',
    meta: {
      title: "PluginExcel"
    },
  },
  {
    name: 'PluginGanttDhtmlx',
    path: '/plugin/gantt/dhtmlx',
    layout: 'base',
    component: 'PluginGanttDhtmlx',
    meta: {
      title: "PluginGanttDhtmlx"
    },
  },
  {
    name: 'PluginGanttVtable',
    path: '/plugin/gantt/vtable',
    layout: 'base',
    component: 'PluginGanttVtable',
    meta: {
      title: "PluginGanttVtable"
    },
  },
  {
    name: 'PluginIcon',
    path: '/plugin/icon',
    layout: 'base',
    component: 'PluginIcon',
    meta: {
      title: "PluginIcon"
    },
  },
  {
    name: 'PluginMap',
    path: '/plugin/map',
    layout: 'base',
    component: 'PluginMap',
    meta: {
      title: "PluginMap"
    },
  },
  {
    name: 'PluginPdf',
    path: '/plugin/pdf',
    layout: 'base',
    component: 'PluginPdf',
    meta: {
      title: "PluginPdf"
    },
  },
  {
    name: 'PluginPinyin',
    path: '/plugin/pinyin',
    layout: 'base',
    component: 'PluginPinyin',
    meta: {
      title: "PluginPinyin"
    },
  },
  {
    name: 'PluginPrint',
    path: '/plugin/print',
    layout: 'base',
    component: 'PluginPrint',
    meta: {
      title: "PluginPrint"
    },
  },
  {
    name: 'PluginSwiper',
    path: '/plugin/swiper',
    layout: 'base',
    component: 'PluginSwiper',
    meta: {
      title: "PluginSwiper"
    },
  },
  {
    name: 'PluginTablesVtable',
    path: '/plugin/tables/vtable',
    layout: 'base',
    component: 'PluginTablesVtable',
    meta: {
      title: "PluginTablesVtable"
    },
  },
  {
    name: 'PluginTypeit',
    path: '/plugin/typeit',
    layout: 'base',
    component: 'PluginTypeit',
    meta: {
      title: "PluginTypeit"
    },
  },
  {
    name: 'PluginVideo',
    path: '/plugin/video',
    layout: 'base',
    component: 'PluginVideo',
    meta: {
      title: "PluginVideo"
    },
  },
  {
    name: 'ProNaiveConfigProvider',
    path: '/pro-naive/ConfigProvider',
    layout: 'base',
    component: 'ProNaiveConfigProvider',
    meta: {
      title: "ProNaiveConfigProvider"
    },
  },
  {
    name: 'ProNaiveFormBasic',
    path: '/pro-naive/form/basic',
    layout: 'base',
    component: 'ProNaiveFormBasic',
    meta: {
      title: "ProNaiveFormBasic"
    },
  },
  {
    name: 'ProNaiveFormQuery',
    path: '/pro-naive/form/query',
    layout: 'base',
    component: 'ProNaiveFormQuery',
    meta: {
      title: "ProNaiveFormQuery"
    },
  },
  {
    name: 'ProNaiveFormStep',
    path: '/pro-naive/form/step',
    layout: 'base',
    component: 'ProNaiveFormStep',
    meta: {
      title: "ProNaiveFormStep"
    },
  },
  {
    name: 'ProNaiveTableRemote',
    path: '/pro-naive/table/remote',
    layout: 'base',
    component: 'ProNaiveTableRemote',
    meta: {
      title: "ProNaiveTableRemote"
    },
  },
  {
    name: 'ProNaiveTableRowEdit',
    path: '/pro-naive/table/row-edit',
    layout: 'base',
    component: 'ProNaiveTableRowEdit',
    meta: {
      title: "ProNaiveTableRowEdit"
    },
  },
  {
    name: 'UserCenter',
    path: '/user-center',
    layout: 'base',
    component: 'UserCenter',
    meta: {
      title: "UserCenter"
    },
  },
  {
    name: 'Wip',
    path: '/wip',
    layout: 'base',
    component: 'Wip',
    meta: {
      title: "Wip"
    },
  }
];
