/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export {}

declare module "vue-router" {
  type RouteNamedMap = import("vue-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "vue-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "vue-router";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "/:pathMatch(.*)*", Record<never, never>, Record<never, never>>;
    "403": RouteRecordInfo<"403", "/403", Record<never, never>, Record<never, never>>;
    "404": RouteRecordInfo<"404", "/404", Record<never, never>, Record<never, never>>;
    "500": RouteRecordInfo<"500", "/500", Record<never, never>, Record<never, never>>;
    "About": RouteRecordInfo<"About", "/about", Record<never, never>, Record<never, never>>;
    "AlovaRequest": RouteRecordInfo<"AlovaRequest", "/alova/request", Record<never, never>, Record<never, never>>;
    "AlovaScenes": RouteRecordInfo<"AlovaScenes", "/alova/scenes", Record<never, never>, Record<never, never>>;
    "DocumentAlova": RouteRecordInfo<"DocumentAlova", "/document/alova", Record<never, never>, Record<never, never>>;
    "DocumentAntd": RouteRecordInfo<"DocumentAntd", "/document/antd", Record<never, never>, Record<never, never>>;
    "DocumentNaive": RouteRecordInfo<"DocumentNaive", "/document/naive", Record<never, never>, Record<never, never>>;
    "DocumentProject": RouteRecordInfo<"DocumentProject", "/document/project", Record<never, never>, Record<never, never>>;
    "DocumentProjectLink": RouteRecordInfo<"DocumentProjectLink", "/document/project-link", Record<never, never>, Record<never, never>>;
    "DocumentProNaive": RouteRecordInfo<"DocumentProNaive", "/document/pro-naive", Record<never, never>, Record<never, never>>;
    "DocumentUnocss": RouteRecordInfo<"DocumentUnocss", "/document/unocss", Record<never, never>, Record<never, never>>;
    "DocumentVideo": RouteRecordInfo<"DocumentVideo", "/document/video", Record<never, never>, Record<never, never>>;
    "DocumentVite": RouteRecordInfo<"DocumentVite", "/document/vite", Record<never, never>, Record<never, never>>;
    "DocumentVue": RouteRecordInfo<"DocumentVue", "/document/vue", Record<never, never>, Record<never, never>>;
    "Exception403": RouteRecordInfo<"Exception403", "/exception/403", Record<never, never>, Record<never, never>>;
    "Exception404": RouteRecordInfo<"Exception404", "/exception/404", Record<never, never>, Record<never, never>>;
    "Exception500": RouteRecordInfo<"Exception500", "/exception/500", Record<never, never>, Record<never, never>>;
    "FunctionMultiTab": RouteRecordInfo<"FunctionMultiTab", "/function/multi-tab", Record<never, never>, Record<never, never>>;
    "FunctionRequest": RouteRecordInfo<"FunctionRequest", "/function/request", Record<never, never>, Record<never, never>>;
    "FunctionSuperPage": RouteRecordInfo<"FunctionSuperPage", "/function/super-page", Record<never, never>, Record<never, never>>;
    "FunctionTab": RouteRecordInfo<"FunctionTab", "/function/tab", Record<never, never>, Record<never, never>>;
    "FunctionToggleAuth": RouteRecordInfo<"FunctionToggleAuth", "/function/toggle-auth", Record<never, never>, Record<never, never>>;
    "Home": RouteRecordInfo<"Home", "/home", Record<never, never>, Record<never, never>>;
    "IframePageUrl": RouteRecordInfo<"IframePageUrl", "/iframe-page/:url", { url: ParamValue<true> }, { url: ParamValue<false> }>;
    "Login": RouteRecordInfo<"Login", "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?", { module?: ParamValueZeroOrOne<true> }, { module?: ParamValueZeroOrOne<false> }>;
    "ManageMenu": RouteRecordInfo<"ManageMenu", "/manage/menu", Record<never, never>, Record<never, never>>;
    "ManageRole": RouteRecordInfo<"ManageRole", "/manage/role", Record<never, never>, Record<never, never>>;
    "ManageUser": RouteRecordInfo<"ManageUser", "/manage/user", Record<never, never>, Record<never, never>>;
    "ManageUserDetailId": RouteRecordInfo<"ManageUserDetailId", "/manage/user-detail/:id", { id: ParamValue<true> }, { id: ParamValue<false> }>;
    "PluginBarcode": RouteRecordInfo<"PluginBarcode", "/plugin/barcode", Record<never, never>, Record<never, never>>;
    "PluginChartsAntv": RouteRecordInfo<"PluginChartsAntv", "/plugin/charts/antv", Record<never, never>, Record<never, never>>;
    "PluginChartsEcharts": RouteRecordInfo<"PluginChartsEcharts", "/plugin/charts/echarts", Record<never, never>, Record<never, never>>;
    "PluginChartsVchart": RouteRecordInfo<"PluginChartsVchart", "/plugin/charts/vchart", Record<never, never>, Record<never, never>>;
    "PluginCopy": RouteRecordInfo<"PluginCopy", "/plugin/copy", Record<never, never>, Record<never, never>>;
    "PluginEditorMarkdown": RouteRecordInfo<"PluginEditorMarkdown", "/plugin/editor/markdown", Record<never, never>, Record<never, never>>;
    "PluginEditorQuill": RouteRecordInfo<"PluginEditorQuill", "/plugin/editor/quill", Record<never, never>, Record<never, never>>;
    "PluginExcel": RouteRecordInfo<"PluginExcel", "/plugin/excel", Record<never, never>, Record<never, never>>;
    "PluginGanttDhtmlx": RouteRecordInfo<"PluginGanttDhtmlx", "/plugin/gantt/dhtmlx", Record<never, never>, Record<never, never>>;
    "PluginGanttVtable": RouteRecordInfo<"PluginGanttVtable", "/plugin/gantt/vtable", Record<never, never>, Record<never, never>>;
    "PluginIcon": RouteRecordInfo<"PluginIcon", "/plugin/icon", Record<never, never>, Record<never, never>>;
    "PluginMap": RouteRecordInfo<"PluginMap", "/plugin/map", Record<never, never>, Record<never, never>>;
    "PluginPdf": RouteRecordInfo<"PluginPdf", "/plugin/pdf", Record<never, never>, Record<never, never>>;
    "PluginPinyin": RouteRecordInfo<"PluginPinyin", "/plugin/pinyin", Record<never, never>, Record<never, never>>;
    "PluginPrint": RouteRecordInfo<"PluginPrint", "/plugin/print", Record<never, never>, Record<never, never>>;
    "PluginSwiper": RouteRecordInfo<"PluginSwiper", "/plugin/swiper", Record<never, never>, Record<never, never>>;
    "PluginTablesVtable": RouteRecordInfo<"PluginTablesVtable", "/plugin/tables/vtable", Record<never, never>, Record<never, never>>;
    "PluginTypeit": RouteRecordInfo<"PluginTypeit", "/plugin/typeit", Record<never, never>, Record<never, never>>;
    "PluginVideo": RouteRecordInfo<"PluginVideo", "/plugin/video", Record<never, never>, Record<never, never>>;
    "ProNaiveConfigProvider": RouteRecordInfo<"ProNaiveConfigProvider", "/pro-naive/ConfigProvider", Record<never, never>, Record<never, never>>;
    "ProNaiveFormBasic": RouteRecordInfo<"ProNaiveFormBasic", "/pro-naive/form/basic", Record<never, never>, Record<never, never>>;
    "ProNaiveFormQuery": RouteRecordInfo<"ProNaiveFormQuery", "/pro-naive/form/query", Record<never, never>, Record<never, never>>;
    "ProNaiveFormStep": RouteRecordInfo<"ProNaiveFormStep", "/pro-naive/form/step", Record<never, never>, Record<never, never>>;
    "ProNaiveTableRemote": RouteRecordInfo<"ProNaiveTableRemote", "/pro-naive/table/remote", Record<never, never>, Record<never, never>>;
    "ProNaiveTableRowEdit": RouteRecordInfo<"ProNaiveTableRowEdit", "/pro-naive/table/row-edit", Record<never, never>, Record<never, never>>;
    "UserCenter": RouteRecordInfo<"UserCenter", "/user-center", Record<never, never>, Record<never, never>>;
    "Wip": RouteRecordInfo<"Wip", "/wip", Record<never, never>, Record<never, never>>
  }
}
